/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.49
 * Generated at: 2019-02-18 18:56:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class product_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1547659512490L));
    _jspx_dependants.put("jar:file:/C:/dev/workspace_spring/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/shop/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<html class=\"no-js\">\n");
      out.write("<head>\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\" />\n");
      out.write("<title>Product page</title>\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/foundation.css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- Start Top Bar -->\n");
      out.write("\t<div class=\"top-bar\">\n");
      out.write("\t\t<div class=\"top-bar-left\">\n");
      out.write("\t\t\t<ul class=\"dropdown menu\" data-dropdown-menu=\"\" role=\"menubar\"\n");
      out.write("\t\t\t\tdata-e=\"n2avhw-e\">\n");
      out.write("\t\t\t\t<li class=\"menu-text\" role=\"menuitem\">Yeti Store</li>\n");
      out.write("\t\t\t\t<li class=\"has-submenu is-dropdown-submenu-parent opens-right\"\n");
      out.write("\t\t\t\t\trole=\"menuitem\" aria-haspopup=\"true\" aria-label=\"One\"><a\n");
      out.write("\t\t\t\t\thref=\"#\">One</a>\n");
      out.write("\t\t\t\t\t<ul class=\"submenu menu vertical is-dropdown-submenu first-sub\"\n");
      out.write("\t\t\t\t\t\tdata-submenu=\"\" role=\"menu\">\n");
      out.write("\t\t\t\t\t\t<li role=\"menuitem\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"is-submenu-item is-dropdown-submenu-item\"><a href=\"#\">One</a></li>\n");
      out.write("\t\t\t\t\t\t<li role=\"menuitem\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"is-submenu-item is-dropdown-submenu-item\"><a href=\"#\">Two</a></li>\n");
      out.write("\t\t\t\t\t\t<li role=\"menuitem\"\n");
      out.write("\t\t\t\t\t\t\tclass=\"is-submenu-item is-dropdown-submenu-item\"><a href=\"#\">Three</a></li>\n");
      out.write("\t\t\t\t\t</ul></li>\n");
      out.write("\t\t\t\t<li role=\"menuitem\"><a href=\"#\">Two</a></li>\n");
      out.write("\t\t\t\t<li role=\"menuitem\"><a href=\"#\">Three</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"top-bar-right\">\n");
      out.write("\t\t\t<ul class=\"menu\">\n");
      out.write("\t\t\t\t<li><input type=\"search\" placeholder=\"Search\"></li>\n");
      out.write("\t\t\t\t<li><button type=\"button\" class=\"button\">Search</button></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<!-- End Top Bar -->\n");
      out.write("\t<br>\n");
      out.write("\t<!-- You can now combine a row and column if you just need a 12 column row -->\n");
      out.write("\t<article class=\"grid-container\">\n");
      out.write("\t\t<div class=\"grid-x cell\">\n");
      out.write("\t\t\t<nav aria-label=\"You are here:\" role=\"navigation\">\n");
      out.write("\t\t\t\t<ul class=\"breadcrumbs\">\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Features</a></li>\n");
      out.write("\t\t\t\t\t<li class=\"disabled\">Gene Splicing</li>\n");
      out.write("\t\t\t\t\t<li><span class=\"show-for-sr\">Current: </span> Cloning</li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"grid-x grid-margin-x\">\n");
      out.write("\t\t\t<div class=\"medium-6 cell\">\n");
      out.write("\t\t\t\t<img class=\"thumbnail\" src=\"resources/product-img/sample1.jpg\"\n");
      out.write("\t\t\t\t\twidth=\"650\" height=\"350\">\n");
      out.write("\t\t\t\t<div class=\"grid-x grid-padding-x small-up-4\">\n");
      out.write("\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/product-img/sample1.jpg\" width=\"200\"\n");
      out.write("\t\t\t\t\t\t\theight=\"200\" align=\"middle\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t<img src=\"resources/product-img/sample1.jpg\" width=\"200\"\n");
      out.write("\t\t\t\t\t\t\theight=\"200\" align=\"middle\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"medium-6 large-5 cell large-offset-1\">\n");
      out.write("\t\t\t\t<h3>설명</h3>\n");
      out.write("\t\t\t\t<p>옵션선택하면 수량 선택 보여주기</p>\n");
      out.write("\t\t\t\t<label>옵션 <select>\n");
      out.write("\t\t\t\t\t\t<option value=\"husker\">Small</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"starbuck\">Medium</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"hotdog\">Large</option>\n");
      out.write("\t\t\t\t\t\t<option value=\"apollo\">Yeti</option>\n");
      out.write("\t\t\t\t</select>\n");
      out.write("\t\t\t\t</label>\n");
      out.write("\t\t\t\t<div class=\"grid-x\">\n");
      out.write("\t\t\t\t\t<div class=\"small-3 cell\">\n");
      out.write("\t\t\t\t\t\t<label for=\"middle-label\" class=\"middle\">Quantity</label>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"small-9 cell\">\n");
      out.write("\t\t\t\t\t\t<input type=\"text\" id=\"middle-label\"\n");
      out.write("\t\t\t\t\t\t\tplaceholder=\"One fish two fish\">\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"button-group expanded\">\n");
      out.write("\t\t\t\t\t<a href=\"#\" class=\"button large\">장바구니 담기</a> <a href=\"#\"\n");
      out.write("\t\t\t\t\t\tclass=\"button large\">바로 구매하기</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"\">\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t<ul class=\"tabs\" data-tabs=\"\" id=\"example-tabs\" role=\"tablist\"\n");
      out.write("\t\t\t\tdata-e=\"af0r5m-e\">\n");
      out.write("\t\t\t\t<li class=\"tabs-title is-active\" role=\"presentation\">\n");
      out.write("\t\t\t\t<a href=\"#panel1\" aria-selected=\"true\" role=\"tab\" aria-controls=\"panel1\" id=\"panel1-label\" tabindex=\"0\">상품리뷰</a></li>\n");
      out.write("\t\t\t\t<li class=\"tabs-title\" role=\"presentation\">\n");
      out.write("\t\t\t\t<a href=\"#panel2\" role=\"tab\" aria-controls=\"panel2\" aria-selected=\"false\" id=\"panel2-label\" tabindex=\"-1\">연관상품</a></li>\n");
      out.write("\t\t\t\t<li class=\"tabs-title\" role=\"presentation\">\n");
      out.write("\t\t\t\t<a href=\"#panel3\" role=\"tab\" aria-controls=\"panel3\" aria-selected=\"false\" id=\"panel3-label\" tabindex=\"-1\">판매자정보</a></li>\n");
      out.write("\t\t\t\t<li class=\"tabs-title\" role=\"presentation\">\n");
      out.write("\t\t\t\t<a href=\"#panel4\" role=\"tab\" aria-controls=\"panel4\" aria-selected=\"false\" id=\"panel4-label\" tabindex=\"-1\">Q&A</a></li>\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t<div class=\"tabs-content\" data-tabs-content=\"example-tabs\">\n");
      out.write("\t\t\t\t<div class=\"tabs-panel is-active\" id=\"panel1\" role=\"tabpanel\"\n");
      out.write("\t\t\t\t\taria-labelledby=\"panel1-label\">\n");
      out.write("\t\t\t\t\t<h4>상품리뷰</h4>\n");
      out.write("\t\t\t\t\t<div class=\"media-object stack-for-small\">\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/200x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<h5>Mike Stevenson</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>I'm going to improvise. Listen, there's something you\n");
      out.write("\t\t\t\t\t\t\t\tshould know about me... about inception. An idea is like a\n");
      out.write("\t\t\t\t\t\t\t\tvirus, resilient, highly contagious. The smallest seed of an\n");
      out.write("\t\t\t\t\t\t\t\tidea can grow. It can grow to define or destroy you.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"media-object stack-for-small\">\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/200x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<h5>Mike Stevenson</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>I'm going to improvise. Listen, there's something you\n");
      out.write("\t\t\t\t\t\t\t\tshould know about me... about inception. An idea is like a\n");
      out.write("\t\t\t\t\t\t\t\tvirus, resilient, highly contagious. The smallest seed of an\n");
      out.write("\t\t\t\t\t\t\t\tidea can grow. It can grow to define or destroy you</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"media-object stack-for-small\">\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/200x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<h5>Mike Stevenson</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>I'm going to improvise. Listen, there's something you\n");
      out.write("\t\t\t\t\t\t\t\tshould know about me... about inception. An idea is like a\n");
      out.write("\t\t\t\t\t\t\t\tvirus, resilient, highly contagious. The smallest seed of an\n");
      out.write("\t\t\t\t\t\t\t\tidea can grow. It can grow to define or destroy you</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<label> My Review <textarea placeholder=\"None\"></textarea>\n");
      out.write("\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t<button class=\"button\">Submit Review</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"tabs-panel\" id=\"panel2\" role=\"tabpanel\"\n");
      out.write("\t\t\t\t\taria-labelledby=\"panel2-label\" aria-hidden=\"true\">\n");
      out.write("\t\t\t\t\t<div class=\"grid-x grid-margin-x medium-up-3 large-up-5\">\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"tabs-panel\" id=\"panel3\" role=\"tabpanel\"\n");
      out.write("\t\t\t\t\taria-labelledby=\"panel3-label\" aria-hidden=\"true\">\n");
      out.write("\t\t\t\t\t<h4>상품리뷰</h4>\n");
      out.write("\t\t\t\t\t<div class=\"media-object stack-for-small\">\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/200x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<h5>Mike Stevenson</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>I'm going to improvise. Listen, there's something you\n");
      out.write("\t\t\t\t\t\t\t\tshould know about me... about inception. An idea is like a\n");
      out.write("\t\t\t\t\t\t\t\tvirus, resilient, highly contagious. The smallest seed of an\n");
      out.write("\t\t\t\t\t\t\t\tidea can grow. It can grow to define or destroy you.</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"media-object stack-for-small\">\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/200x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<h5>Mike Stevenson</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>I'm going to improvise. Listen, there's something you\n");
      out.write("\t\t\t\t\t\t\t\tshould know about me... about inception. An idea is like a\n");
      out.write("\t\t\t\t\t\t\t\tvirus, resilient, highly contagious. The smallest seed of an\n");
      out.write("\t\t\t\t\t\t\t\tidea can grow. It can grow to define or destroy you</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<div class=\"media-object stack-for-small\">\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/200x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"media-object-section\">\n");
      out.write("\t\t\t\t\t\t\t<h5>Mike Stevenson</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>I'm going to improvise. Listen, there's something you\n");
      out.write("\t\t\t\t\t\t\t\tshould know about me... about inception. An idea is like a\n");
      out.write("\t\t\t\t\t\t\t\tvirus, resilient, highly contagious. The smallest seed of an\n");
      out.write("\t\t\t\t\t\t\t\tidea can grow. It can grow to define or destroy you</p>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t<label> My Review <textarea placeholder=\"None\"></textarea>\n");
      out.write("\t\t\t\t\t</label>\n");
      out.write("\t\t\t\t\t<button class=\"button\">Submit Review</button>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"tabs-panel\" id=\"panel4\" role=\"tabpanel\"\n");
      out.write("\t\t\t\t\taria-labelledby=\"panel4-label\" aria-hidden=\"true\">\n");
      out.write("\t\t\t\t\t<div class=\"grid-x grid-margin-x medium-up-3 large-up-5\">\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t<div class=\"cell\">\n");
      out.write("\t\t\t\t\t\t\t<img class=\"thumbnail\" src=\"https://placehold.it/350x200\"\n");
      out.write("\t\t\t\t\t\t\t\thidden=\"\" style=\"display: none !important;\">\n");
      out.write("\t\t\t\t\t\t\t<h5>\n");
      out.write("\t\t\t\t\t\t\t\tOther Product <small>$22</small>\n");
      out.write("\t\t\t\t\t\t\t</h5>\n");
      out.write("\t\t\t\t\t\t\t<p>In condimentum facilisis porta. Sed nec diam eu diam\n");
      out.write("\t\t\t\t\t\t\t\tmattis viverra. Nulla fringilla, orci ac euismod semper, magna\n");
      out.write("\t\t\t\t\t\t\t\tdiam.</p>\n");
      out.write("\t\t\t\t\t\t\t<a href=\"#\" class=\"button hollow tiny expanded\">Buy Now</a>\n");
      out.write("\t\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t</div>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t<div class=\"grid-x align-justify align-middle\">\n");
      out.write("\t\t\t<div class=\"small-12 medium-shrink cell\">\n");
      out.write("\t\t\t\t<ul class=\"menu\">\n");
      out.write("\t\t\t\t\t<li class=\"align-self-middle\">Yeti Store</li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Home</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">About</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Contact</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"small-12 medium-shrink cell\">\n");
      out.write("\t\t\t\t<span>Copyright 2018</span>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</article>\n");
      out.write("\t<script src=\"resources/js/vendor/jquery.js\"></script>\n");
      out.write("\t<script src=\"resources/js/vendor/foundation.js\"></script>\n");
      out.write("\t<script src=\"resources/js/app.js\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
